<?xml version="1.0" ?>
<robot name="jueying" 
    xmlns:xacro="http://www.ros.org/wiki/xacro">

    <material name="black">
        <color rgba="0.0 0.0 0.0 1.0"/>
    </material>
    <material name="grey">
        <color rgba="0.35 0.35 0.35 1.0"/>
    </material>
    <material name="red">
        <color rgba="1.0 0.0 0.0 0.7"/>
    </material>
    <material name="green">
        <color rgba="0.0 1.0 0.0 0.6"/>
    </material>
    <material name="blue">
        <color rgba="0.0 0.0 1.0 0.6"/>
    </material>
    <material name="lightgrey">
        <color rgba="0.5 0.5 0.5 1.0"/>
    </material>
    <material name="silver">
        <color rgba="0.913725490196 0.913725490196 0.847058823529 1.0"/>
    </material>
    <material name="white">
        <color rgba="1.0 1.0 1.0 1.0"/>
    </material>

    <xacro:property name="motor_torque" value="0.5"/>
    <xacro:property name="motor_vec" value="0.1"/>
    <xacro:property name="motor_damp" value="0.01"/>
    <xacro:property name="motor_fric" value="0.1"/>
    <xacro:property name="PI" value="3.14159265359"/>
    <xacro:property name="body_l" value="0.11"/>
    <xacro:property name="body_w" value="0.1"/>
    <xacro:property name="body_h" value="0.11"/>
    <xacro:property name="head_l" value="0.05"/>
    <xacro:property name="hand_height" value="0.03"/>
    <xacro:property name="hand_l1" value="0.025"/>
    <xacro:property name="hand_l2" value="0.048"/>
    <xacro:property name="hand_l3" value="0.108"/>
    <xacro:property name="leg_l1" value="0.048"/>
    <xacro:property name="leg_l2" value="0.05"/>
    <xacro:property name="leg_l3" value="0.05"/>
    <xacro:property name="leg_l4" value="0.04"/>
    <xacro:property name="leg_offset" value="0.026"/>
    <xacro:property name="arm_width" value="0.058"/>
    <xacro:property name="arm_thick" value="0.02"/>
    <xacro:property name="foot_length" value="0.115"/>
    <xacro:property name="foot_width" value="0.068"/>
    <xacro:property name="foot_height" value="0.02"/>
    <xacro:property name="link_weight" value="0.05"/>


    <link name="origin_link">
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <mass value="0.000001" />
            <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0" />
        </inertial>
    </link>
    <joint name="origin_baselink_joint" type="fixed">
        <origin xyz="0 0 0.26" rpy="0 0 0"/>
        <parent link="origin_link"/>
        <child link="base_link"/>
    </joint>
    <link name="base_link">
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
            <mass value="0.8" />
            <inertia ixx="0.0016" ixy="1e-10" ixz="1e-10" iyy="0.0016" iyz="1e-10" izz="0.0016" />
        </inertial>
        <visual>
            <origin xyz="0 0 ${-hand_height}" rpy="0 0 0" />
            <geometry>
                <box size="${body_l} ${body_w} ${body_h}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${body_l} ${body_w} ${body_h}"/>
            </geometry>
        </collision>
    </link>
    <joint name="head_joint" type="fixed">
        <origin xyz="0 0 0.07" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="head_link"/>
    </joint>
    <link name="head_link">
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
            <mass value="0.04" />
            <inertia ixx="1e-5" ixy="1e-12" ixz="1e-12" iyy="1e-5" iyz="1e-12" izz="1e-5" />
        </inertial>
        <visual>
            <origin xyz="0 0 ${-hand_height}" rpy="0 0 0" />
            <geometry>
                <sphere radius="${head_l/2.0}"/>
            </geometry>
            <material name="green"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <sphere radius="${head_l/2.0}"/>
            </geometry>
        </collision>
    </link>
    <xacro:macro name="aelos_hand" params="name is_right">
        <joint name="${name}_joint1" type="revolute">
            <origin xyz="0 ${is_right*(body_w/2)} 0" rpy="0 0 0" />
            <parent link="base_link" />
            <child link="${name}_link1" />
            <axis xyz="0 1 0" />
            <limit lower="${-PI/2.0}" upper="${PI/2.0}" effort="${motor_torque}" velocity="${motor_vec}" />
            <dynamics damping="${motor_damp}" friction="${motor_fric}" />
        </joint>
        <link name="${name}_link1">
            <inertial>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
                <mass value="${link_weight}" />
                <inertia ixx="1e-7" ixy="1e-10" ixz="1e-10" iyy="1e-7" iyz="1e-10" izz="1e-7" />
            </inertial>
            <visual>
                <origin xyz="0 ${is_right*hand_l1/2} 0" rpy="0 0 0" />
                <geometry>
                    <box size="${arm_width} ${hand_l1} ${arm_thick}"/>
                </geometry>
                <material name="blue"/>
            </visual>
        </link>
        <joint name="${name}_joint2" type="revolute">
            <origin xyz="0 ${is_right*hand_l1} 0" rpy="0 0 0" />
            <parent link="${name}_link1" />
            <child link="${name}_link2" />
            <axis xyz="1 0 0" />
            <limit lower="${-PI/2.0}" upper="${PI/2.0}" effort="${motor_torque}" velocity="${motor_vec}" />
            <dynamics damping="${motor_damp}" friction="${motor_fric}" />
        </joint>
        <link name="${name}_link2">
            <inertial>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
                <mass value="${link_weight}" />
                <inertia ixx="1e-7" ixy="1e-10" ixz="1e-10" iyy="1e-7" iyz="1e-10" izz="1e-7" />
            </inertial>
            <visual>
                <origin xyz="0 ${is_right*hand_l2/2} 0" rpy="0 0 0" />
                <geometry>
                    <box size="${arm_width} ${hand_l2} ${arm_thick}"/>
                </geometry>
                <material name="green"/>
            </visual>
        </link>
        <joint name="${name}_joint3" type="revolute">
            <origin xyz="0 ${is_right*hand_l2} 0" rpy="0 0 0" />
            <parent link="${name}_link2" />
            <child link="${name}_link3" />
            <axis xyz="1 0 0" />
            <limit lower="${-PI/2.0}" upper="${PI/2.0}" effort="${motor_torque}" velocity="${motor_vec}" />
            <dynamics damping="${motor_damp}" friction="${motor_fric}" />
        </joint>
        <link name="${name}_link3">
            <inertial>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
                <mass value="${link_weight}" />
                <inertia ixx="1e-7" ixy="1e-10" ixz="1e-10" iyy="1e-7" iyz="1e-10" izz="1e-7" />
            </inertial>
            <visual>
                <origin xyz="0 ${is_right*hand_l3/2} 0" rpy="0 0 0" />
                <geometry>
                    <box size="${arm_width} ${hand_l3} ${arm_thick}"/>
                </geometry>
                <material name="blue"/>
            </visual>
        </link>
    </xacro:macro>
    <xacro:aelos_hand name="hand_left" is_right= "1"/>
    <xacro:aelos_hand name="hand_right" is_right= "-1"/>

    <xacro:macro name="aelos_leg" params="name is_right">
        <joint name="${name}_joint1" type="revolute">
            <origin xyz="0.02 ${is_right*leg_offset} -0.065" rpy="0 0 0" />
            <parent link="base_link" />
            <child link="${name}_link1" />
            <axis xyz="1 0 0" />
            <limit lower="${-PI/2.0}" upper="${PI/2.0}" effort="${motor_torque}" velocity="${motor_vec}" />
            <dynamics damping="${motor_damp}" friction="${motor_fric}" />
        </joint>
        <link name="${name}_link1">
            <inertial>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
                <mass value="${link_weight}" />
                <inertia ixx="1e-7" ixy="1e-10" ixz="1e-10" iyy="1e-7" iyz="1e-10" izz="1e-7" />
            </inertial>
            <visual>
                <origin xyz="0 ${is_right*0.004} ${-leg_l1/2}" rpy="0 0 0" />
                <geometry>
                    <box size="${arm_thick} ${arm_width} ${leg_l1}"/>
                </geometry>
                <material name="blue"/>
            </visual>
            <collision>
                <origin xyz="0 ${is_right*0.004} ${-leg_l1/2}" rpy="0 0 0" />
                <geometry>
                    <box size="${arm_thick} ${arm_width} ${leg_l1}"/>
                </geometry>
            </collision>
        </link>
        <joint name="${name}_joint2" type="revolute">
            <origin xyz="0 0 ${-leg_l1}" rpy="0 0 0" />
            <parent link="${name}_link1" />
            <child link="${name}_link2" />
            <axis xyz="0 1 0" />
            <limit lower="${-PI/2.0}" upper="${PI/2.0}" effort="${motor_torque}" velocity="${motor_vec}" />
            <dynamics damping="${motor_damp}" friction="${motor_fric}" />
        </joint>
        <link name="${name}_link2">
            <inertial>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
                <mass value="${link_weight}" />
                <inertia ixx="1e-7" ixy="1e-10" ixz="1e-10" iyy="1e-7" iyz="1e-10" izz="1e-7" />
            </inertial>
            <visual>
                <origin xyz="0 ${is_right*0.004} ${-leg_l2/4}" rpy="0 0 0" />
                <geometry>
                    <box size="${arm_thick} ${arm_width} ${leg_l2/2}"/>
                </geometry>
                <material name="green"/>
            </visual>
            <visual>
                <origin xyz="${-leg_l2/4} ${is_right*0.004} ${-leg_l2/4*3}" rpy="0 ${PI/4} 0" />
                <geometry>
                    <box size="${arm_thick} ${arm_width} ${leg_l2/2/sin(PI/4)}"/>
                </geometry>
                <material name="green"/>
            </visual>
            <collision>
                <origin xyz="0 ${is_right*0.004} ${-leg_l2/4}" rpy="0 0 0" />
                <geometry>
                    <box size="${arm_thick} ${arm_width} ${leg_l2/2}"/>
                </geometry>
            </collision>
            <collision>
                <origin xyz="${-leg_l2/4} ${is_right*0.004} ${-leg_l2/4*3}" rpy="0 ${PI/4} 0" />
                <geometry>
                    <box size="${arm_thick} ${arm_width} ${leg_l2/2/sin(PI/4)}"/>
                </geometry>
            </collision>
        </link>
        <joint name="${name}_joint3" type="revolute">
            <origin xyz="-0.02 0 ${-leg_l2}" rpy="0 0 0" />
            <parent link="${name}_link2" />
            <child link="${name}_link3" />
            <axis xyz="0 1 0" />
            <limit lower="${-PI/2.0}" upper="${PI/2.0}" effort="${motor_torque}" velocity="${motor_vec}" />
            <dynamics damping="${motor_damp}" friction="${motor_fric}" />
        </joint>
        <link name="${name}_link3">
            <inertial>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
                <mass value="${link_weight}" />
                <inertia ixx="1e-7" ixy="1e-10" ixz="1e-10" iyy="1e-7" iyz="1e-10" izz="1e-7" />
            </inertial>
            <visual>
                <origin xyz="0 ${is_right*0.004} ${-leg_l3/2}" rpy="0 0 0" />
                <geometry>
                    <box size="${arm_thick} ${arm_width} ${leg_l3}"/>
                </geometry>
                <material name="blue"/>
            </visual>
            <collision>
                <origin xyz="0 ${is_right*0.004} ${-leg_l3/2}" rpy="0 0 0" />
                <geometry>
                    <box size="${arm_thick} ${arm_width} ${leg_l3}"/>
                </geometry>
            </collision>
        </link>
        <joint name="${name}_joint4" type="revolute">
            <origin xyz="0 0 ${-leg_l3}" rpy="0 0 0" />
            <parent link="${name}_link3" />
            <child link="${name}_link4" />
            <axis xyz="0 1 0" />
            <limit lower="${-PI/2.0}" upper="${PI/2.0}" effort="${motor_torque}" velocity="${motor_vec}" />
            <dynamics damping="${motor_damp}" friction="${motor_fric}" />
        </joint>
        <link name="${name}_link4">
            <inertial>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
                <mass value="${link_weight}" />
                <inertia ixx="1e-7" ixy="1e-10" ixz="1e-10" iyy="1e-7" iyz="1e-10" izz="1e-7" />
            </inertial>
            <visual>
                <origin xyz="0 ${is_right*0.004} ${-leg_l4/2}" rpy="0 0 0" />
                <geometry>
                    <box size="${arm_thick} ${arm_width} ${leg_l4}"/>
                </geometry>
                <material name="green"/>
            </visual>
            <collision>
                <origin xyz="0 ${is_right*0.004} ${-leg_l4/2}" rpy="0 0 0" />
                <geometry>
                    <box size="${arm_thick} ${arm_width} ${leg_l4}"/>
                </geometry>
            </collision>
        </link>
        <joint name="${name}_joint5" type="revolute">
            <origin xyz="0 0 ${-leg_l4}" rpy="0 0 0" />
            <parent link="${name}_link4" />
            <child link="${name}_link5" />
            <axis xyz="1 0 0" />
            <limit lower="${-PI/2.0}" upper="${PI/2.0}" effort="${motor_torque}" velocity="${motor_vec}" />
            <dynamics damping="${motor_damp}" friction="${motor_fric}" />
        </joint>
        <link name="${name}_link5">
            <inertial>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
                <mass value="${link_weight}" />
                <inertia ixx="1e-7" ixy="1e-10" ixz="1e-10" iyy="1e-7" iyz="1e-10" izz="1e-7" />
            </inertial>
            <visual>
                <origin xyz="0 ${is_right*0.008} ${-foot_height/2}" rpy="0 0 0" />
                <geometry>
                    <box size="${foot_length} ${foot_width} ${foot_height}"/>
                </geometry>
                <material name="blue"/>
            </visual>
            <collision>
                <origin xyz="0 ${is_right*0.008} ${-foot_height/2}" rpy="0 0 0" />
                <geometry>
                    <box size="${foot_length} ${foot_width} ${foot_height}"/>
                </geometry>
            </collision>
        </link>
    </xacro:macro>
    <xacro:aelos_leg name="leg_left" is_right= "-1"/>
    <xacro:aelos_leg name="leg_right" is_right= "1"/>
</robot>
  
